### ISSUE TITLE
Changing progress bar from determinate to indeterminate leaves the animation on

### ISSUE THREAD

**Issue by Mgamerz** [benruehl/adonis-ui#101]
**Describe the bug**
According to the documentation, there is an additional setting for animating a deterministic progress bar, which is on by default. This makes a kind of 'filling up' animation. The documentation states this is only for determinate and not indeterminate progress bars, and the example picture shown does not have this animation on. 

When changing a progress bar to indeterminate (through a binded property), this setting is not turned off, which makes the indeterminate progress bar kind of weird looking as it has the foreground 'fill up' while the piece is moving. This causes weird catch up and slow down and color changes, and it just looks out of place.

**To Reproduce**
1. Set up a determinate progress bar with a binding to set if it is indeterminate or not.
2. Set the progress bar from determinate to indeterminate

**Expected behavior**
It should look like the documentation - where there is no animated 'filling up', as it makes it look weird.

**Screenshots**
Here's a video showing it:
https://i.imgur.com/Qgm1jed.mp4

Notice how when it becomes indeterminate the moving piece changes color and at a few points you can see the 'filling up' color change.

**Additional context**
This has been present since I started using Adonis back in September 2019. I am not 100% sure but this might also be the source of another issue I have where the animation for the determinate progress bar only starts at a certain percentage, like 70% and above, in certain cases. I'm not entirely sure of a reproducible sample for that one though.

I tested this on your latest commits - I just merged them into my project's slightly modified source version.

**Comment by benruehl** [comment]
It is fixed now. Thank you for the detailed and well-written report.
