### ISSUE TITLE
Documentation website is broken

### ISSUE THREAD

**Issue by micah686** [benruehl/adonis-ui#108]
**Describe the bug**
There is a giant gray box that obscures the content, and you can't scroll all the way down

**To Reproduce**
Go to the documentation website

**Expected behavior**
Have the website behave normally

**Screenshots**
![image](https://user-images.githubusercontent.com/3616220/85960155-37a35b00-b956-11ea-9b54-f4c9ac48018a.png)

**Additional context**

**Comment by benruehl** [comment]
Oh my god that looks awful. Thanks for notifying me. I will look into this.

**Comment by benruehl** [comment]
The Jekyll theme "Just The Docs" that is used for the documentation website published a release recently which seems to cause the issue.

I created an issue over there.
https://github.com/pmarsceill/just-the-docs/issues/365

**Comment by benruehl** [comment]
The maintainers of Just The Docs told me a way to use the previous version of the theme.
So this is now fixed via 89c64a2.
