### ISSUE TITLE
Layout is changed when enabling Adonis for switching between dark and light schemes

### ISSUE THREAD

**Issue by McTopaz** [benruehl/adonis-ui#116]
I have a WPF-application where I have done all the steps to enable switching between dark and light themes.

When I add the boilerplate code of Adonis to be able to switch between dark and light schemes, the layout in my MainWindow is changed.

When I say _"add the code to be able to switch between dark and light schemes"_; I mean implementering the [Introduction - Quick start steps in the documentation](https://benruehl.github.io/adonis-ui/docs/getting-started/introduction/).

When the Quick start procedure **is not implemented**; my application looks like this:
![OK Layout](https://user-images.githubusercontent.com/8076594/90730036-bd44e680-e2c7-11ea-852d-2687376126b2.png)

When I implement the Quick start procedure; my application looks like this:
![NOK Layout](https://user-images.githubusercontent.com/8076594/90730168-f3826600-e2c7-11ea-9922-197a036dbc3b.png)
This picture show the light scheme. As that is the default scheme in my application.

The "blue section" in my application is my own UserControl. For some reason the layout of my UserControl has changed when enabling light or dark scheme.
- The space between the "Title" and the "asdf" labels is missing. Same for the space between the "Message" and the "Lorem ipsum..." labels.
- The font weight of the "asdf" and the "Lorem ipsum..." labels have changed to _bold_.
- The text in the buttons is _bold_.
- The text position in the buttons has moved up a bit.
- The size of my UserControl has decreased in height.

The other controls in my application (a Button, a TextBox and a Groupbox) are also affected.

I have narrowed down to the boilerplate code in the _App.xaml_ which cause the layout problems.
Here is my App.xaml code. (Unfortunately I cannot seem to get the code well structured in with GitHub's code section regarding XML-code. You have to believe me that the code is the same as the boilerplate code example).

`
<Application x:Class="Main.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:Main"
             xmlns:adonisUi="clr-namespace:AdonisUI;assembly=AdonisUI"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/AdonisUI;component/ColorSchemes/Light.xaml"/>
                <ResourceDictionary Source="pack://application:,,,/AdonisUI.ClassicTheme;component/Resources.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
`

What could be the problem?

I have attached my application:
Application: [WPF.zip](https://github.com/benruehl/adonis-ui/files/5101539/WPF.zip)
1. Extract the Zip-file.
2. Open the WPF.sln file.
3. If needed, set the _Main project_ as the start up project of the solution.
4. Rebuild the solution
5. Run.

**Comment by benruehl** [comment]
Unfortunately, your solution raises a build error for me:

```
Could not load file or assembly 'file:///C:\<directory of the app>\WPF\packages\Fody.6.1.1\netclassictask\FodyIsolated.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
```

I tried
- closing and reopening VS
- reinstalling PropertyChanged.Fody dependency
- moving the project to a different location

But nothing works.

So only by looking at your code I can say:
- The text is bold because you used labels everywhere. In Adonis UI labels are bold by default. Use `TextBlock` instead if you only want to display text and not label another control.
- There are no spaces because you did not specify any. By default, labels have a padding of `5` which is why there were spaces before. Adonis UI removes these paddings because it tries to establish [unified spacing](https://benruehl.github.io/adonis-ui/docs/guides/space/) throughout the app instead.
- The labels are not centered vertically anymore for the same reason, I guess. Use `VerticalAlignment="Center"` to center them. They might have appeared to be centered before because of the default padding of labels which pushed the text downwards. That's just a guess though as I cannot verify this without running the app.

**Comment by McTopaz** [comment]
Strange about the PropertyChanged/Fody bug...

I'm now on a different computer and got it working without any problem by:
1. Downloaded the WPF.zip.
2. Extraxed the WPF-folder to the Window's desktop.,
3. Opened the WPF.sln file.
4. Rebuilt the **ControlLibrary** project.
5. Rebuilt the **Main** project.
6. Press Run.

I run:
- Windows 7, Home Premium, x64.
- Visual Studio 2019, Communitity, version 16.6.2
- .NET Framework 4.7.2

This should run at your site as well. Strange...

**Comment by McTopaz** [comment]
Thanks for the tips anyway!

- Added _VerticalAlignments_ to some controls,
- Added _Margins_ to some controls.
- Changed all my labels to _TextBlocks_.

With that I managed to fix the appearance satisfactory.

**Comment by benruehl** [comment]
You're right, it's strange. I found [a stackoverflow thread](https://stackoverflow.com/questions/50485510/costura-fody-throwing-error-with-fodyisolated-dll) discussing the issue. The accepted answer suggests to not run the project on a network drive, but I don't even have one.

I'm glad your question is answered now, though. I will close this issue.
