### ISSUE TITLE
Are the Layer4BackgroundBrush and Layer4BorderColor attributes correct linked to the layers?

### ISSUE THREAD

**Issue by McTopaz** [benruehl/adonis-ui#117]
**Describe the bug**
I'm trying to learn how to create my own themes for Adonis. I'm evaluating Adonis for my company if we can use it two switch between dark and light themes with custom colors. I have played around with the colors and see what result I got.
When I change the colors of the _Layer4BackgroundColor_ and _Layer4BorderColor_ parameters and tries this on nested GroupBoxes I don't get the result I think is correct.
**Note:** It possible that the result is correct and I have no clue what I'm doing >_< :P ;)

**To Reproduce**
1. Create a WPF application.
2. Install the Adonis NuGet.
3. My _App.xaml_ and _MainWindow.xaml_ and _MainWindows.xaml.cs_ looks like the XAML-code bellow.
4. My _Light.xaml_ is attached at the bottom. Please change the file extension from _.txt_ to _.xaml_.
5. Add the _Light.xaml_ file to the WPF-project and set the _Build Action_ to _Page_.
6. Alter the MainWindow's constructor with the correct path to the _Light.xaml_.
7. Build and run the application. It should work directly.
8. Please look at the attached screenshot.

**Expected behavior**
I have changed these parameters.
- Layer0BorderColor = 777777 // Gray.
- Layer1BackgroundColor = 00ff00 // Green
- Layer1BorderColor = 007700 // Dark green
- Layer2BackgroundColor = 0000ff // Blue
- Layer2BorderColor = 000077 // Dark blue
- Layer3BackgroundColor = ffff00 // Yellow
- Layer3BorderColor = ff00ff // Purple
- Layer4BackgroundColor = 00ffff // Turquoise
- Layer4BorderColor = ff0000 // Red

(I have added a five level deep nested Groupboxes. As Adonis don't support more than four layers, I'm OK that the fifth layer "inherits" the layer 4 colors.)

- Why is the level 4 groupbox background colored green when it should be turquoise? Layer4BackgroundColor = #00ffff. The GB3 button does have the turquoise color. 
- Why is the level 4 groupbox header bar colored green when it should be red? Layer4Bordercolor = #ff0000.

Please look at the screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/8076594/92615224-2c0cd280-f2bd-11ea-97bf-e8d4a5296dfa.png)

**App.xaml**
`
<Application x:Class="Main.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:Main"
             xmlns:adonisUi="clr-namespace:AdonisUI;assembly=AdonisUI"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/AdonisUI;component/ColorSchemes/Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/AdonisUI.ClassicTheme;component/Resources.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
`

**MainWindow.xaml**

<Window x:Class="Main.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Main"
        xmlns:views="clr-namespace:GTL.Views;assembly=GTL"
        mc:Ignorable="d"
        Title="MainWindow" Height="800" Width="700">

    <Window.Style>
        <Style TargetType="Window" BasedOn="{StaticResource {x:Type Window}}" />
    </Window.Style>
   
    <StackPanel Orientation="Vertical">
        <GroupBox Margin="20" Header="Layer1">
            <StackPanel>
                <Button Width="100" Height="40" Content="GB1" />
                <GroupBox Header="Layer2">
                    <StackPanel>
                        <Button Width="100" Height="40" Content="GB2" />
                        <GroupBox Header="Layer3">
                            <StackPanel>
                                <Button Width="100" Height="40" Content="GB3" />
                                <GroupBox Header="Layer4">
                                    <StackPanel>
                                        <Button Width="100" Height="40" Content="GB4" />
                                        <GroupBox Header="Layer5">
                                            <StackPanel>
                                                <Button Width="100" Height="40" Content="GB5" />
                                            </StackPanel>
                                        </GroupBox>
                                    </StackPanel>
                                </GroupBox>
                            </StackPanel>
                        </GroupBox>
                    </StackPanel>
                </GroupBox>
            </StackPanel>
        </GroupBox>
    </StackPanel>
</Window>

**MainWindow.xaml.cs**

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            var uri = new Uri("pack://application:,,,/Light.xaml", UriKind.Absolute);
            ResourceLocator.SetColorScheme(Application.Current.Resources, uri);
        }
    }

[Light.txt](https://github.com/benruehl/adonis-ui/files/5195997/Light.txt)

**Comment by benruehl** [comment]
Good spot.
I checked your setup and can confirm that group boxes on layer 4 do not use the layer 4 colors correctly.
A fix is on the way.

Besides that, I would be interested in your reasons for and against using the library. Getting feedback is important to improve but sometimes hard to get on this platform.

Thank you for reporting the issue.

**Comment by McTopaz** [comment]
Thanks @benruehl!

I would be pleased to give you feedback regarding my company using your library.
But I'm not sure if this issue/thread is the correct forum for it.
How would you like to receive the feedback?

**Comment by benruehl** [comment]
Awesome, thanks a lot!
You could send me an email. My email address should be visible on my profile.
