### ISSUE TITLE
Does the dark theme support System.Windows.Controls.ToolBarTray

### ISSUE THREAD

**Issue by zhouchaoyuan** [benruehl/adonis-ui#119]
I have a toolbar in my project. when I changed the theme from light theme to dark theme. Only the toolbar stay same.
It seems like it doesn't support System.Windows.Controls.ToolBarTray  System.Windows.Controls.ToolBar

**Comment by benruehl** [comment]
Yes, the `ToolBar` control is still not supported unfortunately. Sorry for that.

Please see #94 for a similar discussion.
