### ISSUE TITLE
.NET Core compatibility

### ISSUE THREAD

**Issue by Atulin** [benruehl/adonis-ui#12]
Microsoft is clearly moving away from the .NET Framework, and WPF itself can run just fine on .NET Core, it might be worth looking into making the code compatible with .NET Core
![image](https://user-images.githubusercontent.com/11233299/54516561-8eeb0b00-495f-11e9-8bb7-fae7ba1fffff.png)

**Comment by nkristek** [comment]
I support this request as .NET Core promises performance gains compared to .NET Framework, but lets not forget .NET Core 3.0 is still in the preview stage. According to the current roadmap it is to be released in the second half of 2019.

**Comment by benruehl** [comment]
I definitely plan to support .NET Core in the future and I am going to investigate what is required to do so soon.
