### ISSUE TITLE
Allow hiding of the window title in the title bar

### ISSUE THREAD

**Issue by marcinkurek** [benruehl/adonis-ui#127]
I would like to accomplish this with Adonis UI:

![Bez tytułu](https://user-images.githubusercontent.com/3824342/96060202-2132f800-0e90-11eb-80bf-b93aae168fca.png)

I tried that by setting `IconVisibility` to `false` and `TitleBar` to an empty string, but that creates two issues:
- There is still a little bit of margin leftmost to the `AdonisWindow.TitleBarContent`, presumably because it's still occupied by a `TextBlock` displaying the empty string
- The `TitleBar` property is used in other places in the system (for example taskbar previews, or the Alt+Tab switcher) so I would prefer it's not empty

I can contribute this change if the feature request gets accepted.

**Comment by benruehl** [comment]
Yes you're right, that's an issue I noticed as well. I think a property `TitleVisibility` would come in handy here.

If you'd like to add this, please just go ahead. This contribution would be very welcome, as well as your other suggestion. Otherwise I will put it on the to-do list.

**Comment by marcinkurek** [comment]
OK I'm picking this up

**Comment by marcinkurek** [comment]
Done: https://github.com/benruehl/adonis-ui/pull/128
