### ISSUE TITLE
Cannot position TabItem headers to left with Adonis UI styled WPF application.

### ISSUE THREAD

**Issue by SwaroopSomanna** [benruehl/adonis-ui#135]
I have a tab control in my WPF application and I'm trying to position the TabItem headers to the left as shown in this MSDN post using the below code (copied from the post):

`<TabControl TabStripPlacement="Left" Margin="0, 0, 0, 10"> <TabItem Name="TabOne" Header="Tab One"> <TabItem.Content> <TextBlock TextWrapping="WrapWithOverflow"> Tab One Here. </TextBlock> </TabItem.Content> </TabItem> <TabItem Name="TabTwo" Header="Tab Two"> <TabItem.Content> <TextBlock TextWrapping="WrapWithOverflow"> Tab Two here. </TextBlock> </TabItem.Content> </TabItem> </TabControl> `

According to the post this is what Im supposed to get:

![1YUJs.png](https://user-images.githubusercontent.com/32904377/97838044-69ae3a80-1d05-11eb-8f90-b8b5a3baa85b.png)

But this is what I'm currently getting:

![unh8p.png](https://user-images.githubusercontent.com/32904377/97838053-6e72ee80-1d05-11eb-8157-dcdc2628028c.png)

I've copied the exact same code from the post to my application and can't understand what has gone wrong. I know this has got something to do with the Adonis UI based styling of of the TabControl because the TabItem gets placed to to the left with the above code in applications that donot use AdonisUI.

Here is my full xaml:

`<Window x:Class="OptionsWindow" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" Title="TabStripPlacementSample" Height="200" Width="250" UseLayoutRounding="True"> <Grid> <TabControl TabStripPlacement="Left" Margin="0,0,33,10"> <TabItem Name="TabOne" Header="Tab One"> <TabItem.Content> <TextBlock TextWrapping="WrapWithOverflow"> Tab One Here. </TextBlock> </TabItem.Content> </TabItem> <TabItem Name="TabTwo" Header="Tab Two"> <TabItem.Content> <TextBlock TextWrapping="WrapWithOverflow"> Tab Two here. </TextBlock> </TabItem.Content> </TabItem> </TabControl> </Grid>`

**Comment by benruehl** [comment]
`TabStripPlacement="Left"` is currently not supported. Sorry for that.

Please see #65 for a similar report. Closing this one because it is a duplicate.
