### ISSUE TITLE
Add project Dawn to your expo page

### ISSUE THREAD

**Issue by Insire** [benruehl/adonis-ui#140]
Hi there,

i have recently written and published a small tool for managing plain file backups using this library.

I'd like you to take a look and consider adding it to your Expo page.

The project can be found [here](https://github.com/Insire/Dawn)

Thanks for your amazing framework 👍 

If you need further information, please don't hesitate to ask :)

**Comment by Insire** [comment]
Added some screenshots and other information to my readme. Feel free to use anything you find there.

**Comment by benruehl** [comment]
Hi,

thanks for suggesting your project!
I'm happy to add it to the Expo.
I'll use the third image of your readme file if that's ok for you.

Sorry for the late reply btw.

**Comment by benruehl** [comment]
I'll go ahead now and add the project.
If you don't like how it's presented just tell me what to change.

**Comment by Insire** [comment]
Thx! I like it the way it is.
