### ISSUE TITLE
Get ForegroundBrush of not currently loaded theme

### ISSUE THREAD

**Issue by IAmJonas1234** [benruehl/adonis-ui#146]
Is there a way to get the ForegroundBrush of the not currently loaded theme (would be black in dark mode and white in light mode) in Xaml?

**Comment by benruehl** [comment]
You could try to load the correct `ResourceDictionary` and get the brush from it.

Something like this:

```csharp
var colorScheme = new ResourceDictionary();
colorScheme.Source =
        new Uri("pack://application:,,,/AdonisUI;component/ColorSchemes/Light.xaml",
                UriKind.RelativeOrAbsolute);
var foreground = colorScheme[Brushes.ForegroundBrush] as Brush;
```

I did not test this code so it might not work exactly like this. ([Source](https://stackoverflow.com/a/25625650))

**Comment by IAmJonas1234** [comment]
Is there a way to do this directly in XAML?

**Comment by benruehl** [comment]
You could wrap this code in some custom dependency property and use it in XAML.
