### ISSUE TITLE
Adding glow around the main window

### ISSUE THREAD

**Issue by micah686** [benruehl/adonis-ui#147]
I have a question regarding the best way to add a glow/colored border like MahApps or MUI does around the main window.
Something like this:
![image](https://user-images.githubusercontent.com/3616220/107003597-e6f0ad80-6741-11eb-9300-a2f3b3165044.png)
![image](https://user-images.githubusercontent.com/3616220/107003618-ee17bb80-6741-11eb-9779-c394105b3188.png)
Do you know of a good way to do this with your project?

**Comment by benruehl** [comment]
When using `AdonisWindow` you can simply set `BorderBrush` to achieve the colored border.  The color of the window drop shadow cannot be changed unfortunately because it is rendered by the OS.

**Comment by micah686** [comment]
Ok, thanks. That was what I was looking for
