### ISSUE TITLE
Sorry for stupid question

### ISSUE THREAD

**Issue by ZhmerenkaSolution** [benruehl/adonis-ui#153]
How to add `ToggleSwitch` on Window in xaml?
![изображение](https://user-images.githubusercontent.com/69646713/112315969-55b6a580-8cb3-11eb-9504-605ba3befa1a.png)
I thot that is custom control and I didn't found that in `<AdnousUi.Controls:ToggleSwitch` or `AdonisUI:ToggleSwitch` or even your documentation.

**Comment by alexhelms** [comment]
The ToggleSwitch is available as a style, see https://benruehl.github.io/adonis-ui/docs/guides/styles-and-templates/

You would do something like this:

```
<Button Style="{DynamicResource {x:Static adonisUi:Styles.ToggleSwitch }}"/>
```

**Comment by benruehl** [comment]
@alexhelms Thanks for answering!
You're right, it's a style. Just a little addition: It targets toggle buttons so you can use it on `ToggleButton` or `CheckBox` for example.

**Comment by ZhmerenkaSolution** [comment]
Yep, that's it, thanks my dudes.
`<ToggleButton Style="{DynamicResource {x:Static adonisUi:Styles.ToggleSwitch }}" />` work fine.
