### ISSUE TITLE
Can I somehow set to ignore control when I change ColorScheme?

### ISSUE THREAD

**Issue by ZhmerenkaSolution** [benruehl/adonis-ui#154]
I have `<WindowsFormsHost><wf:DataGridView`. Adonis dark theme pretty badly changes font here: 
1. Light color scheme
![1](https://user-images.githubusercontent.com/69646713/112975821-c69b0900-915c-11eb-86ea-c788eb612ef8.png)
2. Dark color scheme
![2](https://user-images.githubusercontent.com/69646713/112975822-c7339f80-915c-11eb-8ac4-c10a420eb362.png)

Can I somehow disable colorScheme changing only for `DataGridView`? Or maybe manually set ColorScheme parameters for `DataGridView`?

**Comment by benruehl** [comment]
You could create a style for your DataGrid and set foreground or background colors as you like.

Alternatively, if you don't want to have Adonis UI's default style for DataGrids in general, you need to replace the following line in your `App.xaml`:

```xml
<ResourceDictionary Source="pack://application:,,,/AdonisUI.ClassicTheme;component/Resources.xaml"/>
```

... with your own resource dictionary. Just copy [Adonis UI's resource file](https://github.com/benruehl/adonis-ui/blob/master/src/AdonisUI.ClassicTheme/Resources.xaml) and remove all styles you don't like.
This has the disadvantage that future updates are not applied automatically to your file, of course.
