### ISSUE TITLE
Not sure if I did something wrong but only the root TreeViewItem has a style

### ISSUE THREAD

**Issue by MrMelon54** [benruehl/adonis-ui#163]
Here is an example of my styling issue:
![image](https://user-images.githubusercontent.com/48031324/123182572-ab077c00-d487-11eb-84df-76dda8fc16bd.png)
Here is my xaml source for the tree view
```xml
<TreeView x:Name="NbtTreeElement" SelectedItemChanged="NbtTreeElement_SelectedItemChanged" >
    <TreeView.Resources>
        <Style TargetType="TreeView" BasedOn="{StaticResource {x:Type TreeView}}" />
    </TreeView.Resources>
</TreeView>
```
I am adding the items dynamically in the code using a class which extends `TreeViewItem` and edits the Header and other properties in the constructor.

**Comment by MrMelon54** [comment]
Well I figured something out and it works even if it is a little hacky lol

**Comment by tizu69** [comment]
> Well I figured something out and it works even if it is a little hacky lol

What is your solution? I'm having the same problem and found no solution (I also searched online without success).

**Comment by mrmelon54** [comment]
I recon it was probably this line:
```cs
ItemContainerStyle = (Style)Parent.GetValue(ItemContainerStyleProperty);
```
but I haven't worked on that project in so long so I have no idea if that was actually the fix?
