### ISSUE TITLE
Remove red border around button content when using data validation

### ISSUE THREAD

**Issue by CLJunge** [benruehl/adonis-ui#190]
![Issue](https://user-images.githubusercontent.com/5173200/174281367-bc560965-57b3-4e12-88b2-cbdd7cc8c78a.PNG)

How do I get rid of this border around the button content? It's even showing up when using an image as content. Checked the source but I couldn't find anything related to this. It's definitely not  related to the error color/brush since I changed that to green for testing purposes.

**Comment by FlipFlop17** [comment]
Came looking for an answer to the same question.

**Comment by braydonw** [comment]
@CLJunge  @FlipFlop17 

Came looking for the same thing... did either of you ever figure it out?

**Comment by FlipFlop17** [comment]
> @CLJunge @FlipFlop17
> 
> Came looking for the same thing... did either of you ever figure it out?

No, gave up. Using material design instead

**Comment by CLJunge** [comment]
It's the default error template, you can probably remove the border by overriding it. But I haven't tried that since I also switched to Material Design.

**Comment by zangetsudo** [comment]
AdonisWindow.xaml:

```
<ControlTemplate TargetType="{x:Type local:AdonisWindow}">
<AdornerDecorator> <- 1
//....
</AdornerDecorator>  <- 2
</ControlTemplate>
```
remove above lines of 1/2 will git rid of the 'red border'

if it resoved your problem, please add a thumbs，thanks
