### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SandersAlex** [benruehl/adonis-ui#199]
1. How to create "breadcrumbs" like in the picture - https://github.com/benruehl/adonis-ui/blob/master/docs/img/adonis-demo-switch-color-schemes.gif
2. How to create a window title like in the picture - https://github.com/benruehl/adonis-ui/blob/master/docs/img/adonis-demo-peak-dark.gif

This is not in the documentation and there is no example

Best regards, Alex

**Comment by benruehl** [comment]
Both of these gifs show older versions of the example app. If you want to see how they were done you need to check out the repo and move back a couple commits. I cannot tell you exactly to which commits you'd have to jump to, though.

Alternatively, you could go through older releases as well. See the release notes of v1.14.0 for example. https://github.com/benruehl/adonis-ui/releases/tag/1.14
It says "Rework of Adonis UI Demo app". So when you check out v1.13.0 you should have the state before the rework which might look like the first image you posted. The second image is even older so you have to look even further down in the project's history.

**Comment by SandersAlex** [comment]
Thanks for the complete and detailed answer. I will watch and learn from the best, from you.
