### ISSUE TITLE
visual studio 2022 xaml designer not showing adonisControls:AdonisWindow

### ISSUE THREAD

**Issue by chrishartman2018** [benruehl/adonis-ui#203]
Work switched to visual studio 2022.
  
In vs 2019, the wpf xaml designer shows the designer and the source split for <adonisControls:AdonisWindow....    

VS2022 for the same solution and project only shows the xaml source for xaml those same <adonisControls:AdonisWindow ....  files, ... not recognizing and launching the xaml designer.           It works as expected for other xaml.

Any suggestions on how to resolve this, so that vs2022 recognizes the <adonisControls:AdonisWindow...    files and renders them in the xaml designer?   Thanks

**Comment by chrishartman2018** [comment]
Follow up.   Discovered that (so far) ... on each <adonisControls:AdonisWindow ...    xaml file, .... that if I change it to <Window...   </Window>,    close, save, and reopen, .... that I can restore <adonisControls:AdonisWindow...  ... and the designer then appears to work fine in VS2022.

**Comment by livan3li** [comment]
i cannot see Adonis UI controls in toolbox to add component into window? Can you help?

**Comment by zangetsudo** [comment]
not work with designer here too. please put a screen shot that what you do will be help
