### ISSUE TITLE
MenuItem HotKey not respected

### ISSUE THREAD

**Issue by maximilien-noal** [benruehl/adonis-ui#48]
**Describe the bug**

Once Adonis is used, MenuItem' hotkeys are not respected (they should be), and the underscore is displayed (it should not be)

**To Reproduce**

* Use a MenuItem with an underscore at the beginning of the Header property string.
* Add Adonis-UI nuget package.

**Expected behavior**

The same behavior as vanilla WPF.
* Keyboard navigation should work (Alt + F for a MenuItem Header labeled "_File" for example)
* The MenuItem is displayed as "File", not "_File" (true at runtime AND design time)
* At runtime, after a press on the Alt key, all hotkey'd hints should be displayed

**Comment by benruehl** [comment]
Thanks for reporting, should be fixed now.

**Comment by maximilien-noal** [comment]
Thank you for this amazing project ! :)
