### ISSUE TITLE
ScrollBar - Usability improvements

### ISSUE THREAD

**Issue by Swiftpaws** [benruehl/adonis-ui#55]
The thumb on the scrollbar currently has no min height/width set so it becomes [very small](https://i.imgur.com/bbioyK0.png) once many items have been added. 

Setting a min height/width should help - also I think increasing the width of the thumb itself should be natively possible.

**Comment by benruehl** [comment]
Thanks for pointing this out. An overhaul of the scrollbar style is already planned, so this fits in there very well.

The small size you are experiencing seems to be the result of WPF's default calculation. But it looks like there is a kind of hacky way to specify a mininum size which is explained [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/1a7f71bd-d64f-4341-9b7f-9db90afa6e8b/minheight-on-scrollbar-thumb?forum=wpf). In case you need a quick solution you can copy the [scrollbar style of Adonis UI](https://github.com/benruehl/adonis-ui/blob/master/AdonisUI.ClassicTheme/DefaultStyles/ScrollBar.xaml) into a custom `ResourceDictionary`, modify the `Track` like the MSDN thread suggests and include it in your resources.

**Comment by Swiftpaws** [comment]
Thanks for the reply - As for the overhaul: I think you could get some inspiration from the scrollbar implementation in UWP

**Comment by Mgamerz** [comment]
Another thing that would be very useful is to change the foreground of the scrollbar buttons and thumb. I'm not sure what layer I'm on, but when I have a few controls layered on top of each other, I start to get comboboxes thatl ook like this:

![image](https://user-images.githubusercontent.com/2738836/79061962-eaff8c00-7c52-11ea-939c-07032b11f87d.png)

I've been digging around in the source - it's something in scrollbar.xaml, but I can't figure out how to override the layer colors, I can only do the base. This makes it almost appear like there is no scrollbar.
