### ISSUE TITLE
ListView - Content not rendered

### ISSUE THREAD

**Issue by Swiftpaws** [benruehl/adonis-ui#68]
**Describe the bug**
Seems like the ListViewItem style is causing some issues with the rendering of the listview item content. The text is not visible at all

**To Reproduce**
In my test project I boiled the issue down to the ListViewItem style
https://github.com/Swiftpaws/Adonis-ListViewBug

**Comment by benruehl** [comment]
At the moment, the list view style expects the list view to have a grid view assigned. So adding the following to your demo makes it work:

```xml
<ListView.View>
    <GridView>
        <GridViewColumn Header="Content"
                        DisplayMemberBinding="{Binding Content}" />
    </GridView>
</ListView.View>
```
