### ISSUE TITLE
About using adonis- UI could not close the program properly

### ISSUE THREAD

**Issue by ghost** [benruehl/adonis-ui#69]
When I tried to close the program, it was found that it was not closed normally but was stuck in a math method of adonis. What needs to be explained is that I did not find similar problems in the .netframework environment, but in wpf of .netcore3.1 This problem will occur next, can you give me more information about the method when the program is closed so that I can try to solve it, thank you
![屏幕截图(22)](https://user-images.githubusercontent.com/58246461/74801444-8fc7b200-5311-11ea-96e5-310491dd6881.png)

**Comment by LungMaang** [comment]
![屏幕截图(22)](https://user-images.githubusercontent.com/58246461/74801655-5479b300-5312-11ea-8bc9-b40e8e6435c4.png)

**Comment by benruehl** [comment]
Hard to tell what can cause this without further information.

The `MathConverter` is an implementation by Ivan Krivyakov so I cannot tell you much about it.
https://ikriv.com/dev/wpf/MathConverter/
I use it for layout calculations made directly in XAML in various components, e.g. for building the sum of multiple spaces. I never experienced any issues when using it.

Could you please post the exception type, message and stack trace for further investigation? Do you use the converter yourself or does the error occur internally in Adonis UI?

**Comment by LungMaang** [comment]
Thank you very much for your timely review and response. Before you responded, I initially thought that AdonisWindow of MainView encountered some problems and could not be completely closed, but the problem still persisted when I replaced it with my Window Style. With the more detailed information you provided, I found that the work I did in the beginning was in the wrong direction. In your Adonis UI project (I actually like it), I only use the controls it provides and some common Colors and Brushes. As I am working on the problem, I have not been able to provide you with some valid information for the time being.

From LungMaang
Sent to Mr. Benjamin Rühl
发件人: Benjamin Rühl<mailto:notifications@github.com>
发送时间: 2020年2月19日 20:28
主题: Re: [benruehl/adonis-ui] About using adonis- UI could not close the program properly (#69)


Hard to tell what can cause this without further information.

The MathConverter is an implementation by Ivan Krivyakov so I cannot tell you much about it.
https://ikriv.com/dev/wpf/MathConverter/
I use it for layout calculations made directly in XAML in various components, e.g. for building the sum of multiple spaces. I never experienced any issues when using it.

Could you please post the exception type, message and stack trace for further investigation? Do you use the converter yourself or does the error occur internally in Adonis UI?

―

**Comment by benruehl** [comment]
Closing this because the current state is unclear but the author deleted its account so no further update is expected on this.
