### ISSUE TITLE
AdonisWindow maximise/restore button icon self-update

### ISSUE THREAD

**Issue by DoctorLogiq** [benruehl/adonis-ui#76]
Hi, first of all thank you for this fantastic resource, it's an absolute time-and-eye-saver... **dark themes are a necessity for survival**!

It appears, however, that the maximise/restore button in the window control box of an AdonisWindow doesn't update when the WindowState changes, and I think it would be really nice to see the "restore down" icon when the window is maximised, and of course the "maximise" icon otherwise. Currently I only see the "maximise" icon.

**Comment by benruehl** [comment]
Thanks for reporting this!

It used to work just fine, so it seems to got broken somehow.
I will take a look at this.
