### ISSUE TITLE
Add Image Sort to Expo

### ISSUE THREAD

**Issue by Lolle2000la** [benruehl/adonis-ui#77]
I am using Adonis UI in my app [Image Sort](https://github.com/Lolle2000la/Image-Sort). It really has been a great experience using it!

Now I've seen that you can suggest a project for the Expo page, so I thought I could maybe shamelessly suggest my own project!

Here is a screenshot:

![Screenshot of Image Sort](https://github.com/Lolle2000la/Image-Sort/raw/master/Image-Sort-Screenshot.gif)

**Comment by benruehl** [comment]
Thanks for the suggestion! This will make a great addition.
Suggesting you own work is totally fine, of course.

I will use the following metadata for your project:

- name: Image Sort
- author: Lolle2000la
- tagline: Sorts your image at high speed
- project url: https://github.com/Lolle2000la/Image-Sort

Is that okay for you? Just tell me if you want some of them changed, like pointing to https://imagesort.org/ instead or using a different tagline etc.

**Comment by Lolle2000la** [comment]
That way is good, thank you!
