### ISSUE TITLE
Toolbar Overflow button style

### ISSUE THREAD

**Issue by tgiachi** [benruehl/adonis-ui#94]
**Describe the bug**
Toolbar Overflow button style is white

**To Reproduce**
1. Add toobar in AdonisWindow

**Expected behavior**
I think the toolbar overflow should take the global style

**Screenshots**
![image](https://user-images.githubusercontent.com/942730/81899564-73a77a00-95bb-11ea-8fcb-2a021d843213.png)

**Additional context**
I'm using last nuget version, how I can set style? Thank you, I love your library!

**Comment by alexhelms** [comment]
I actually noticed this too but I forgot to create an issue.

What I did instead is what the demo app does: just make a stack panel and add buttons and make them use the tool bar style. See here: https://github.com/benruehl/adonis-ui/blob/master/src/AdonisUI.Demo/Views/ButtonReference.xaml#L62

It isn't an actual toolbar, but maybe it will do what you need for now.

**Comment by tgiachi** [comment]
Thank you! Great solution!

**Comment by benruehl** [comment]
The `ToolBar` control is one of the few remaining controls that are not covered by Adonis UI yet. Sorry for that.
I will add this to the to do list.

**Comment by tgiachi** [comment]
No problem @benruehl, I love your library anyway!
